# Prendre des notes dans un notebook

Voici une bonne façon de garder des notes utiles dans un notebook, sans tomber dans les docstrings ou les arguments de fonctions.

## Comment noter
- Utilise des cellules Markdown pour les explications.
- Écris des phrases courtes et claires.
- Sépare toujours : le concept, le code, l’observation et la conclusion.
- Ajoute des titres et des puces pour garder la structure lisible.

## Ce qu’il faut noter
- Le concept important à retenir.
- Ce que tu as compris ou compris différemment.
- Ce que tu as observé lors de l’exécution.
- Une erreur ou un piège rencontré.
- Une question à garder en tête.
- La prochaine étape à tester.

## Format simple à réutiliser
- Objectif :
- Observation :
- Hypothèse :
- Vérification :
- Conclusion :

## À éviter
- Écrire tout le code en prose.
- Répéter ce qui est déjà évident dans le code.
- Mettre trop de détails inutiles.

L’idée, c’est de noter ce que le notebook t’apprend, pas de refaire le code ligne par ligne.

In [5]:
print("Hello World!")

Hello World!


## Premier cours sur numpy 

Au lieu d'utiliser des listes classiques en python, on va plus plutot utiliser des 
***ndarray** qui sont tableaux (objet) en python de la biblio Numpy. On d'abord donc des tableaux a : 
- 1 dimension
- 2 dimensions
- 3 dimenions...
- n dimensions

Mais dans notre contexte, on travaillera le plus souvent avec des tableaux a deux dimensions. On peut donc y stocker des valeurs de meme type par ligne et par colonne. on peut egalement y stocker les pixels d'une image (valeur = 0-250). 

## Quelques attributs :

In [ ]:
ndim = 1
shape = (2, ) #C'est un tuple 

## Quelques contructeurs : 

In [7]:
import numpy as np

In [17]:
A = np.array([1, 2, 3]) ### Tab de dim 1 
A.ndim
A.shape
A.size #La taille du tableau, le nombre d'éléments dans le tableau

#########Initialisation d'un tableau avec des valeurs
np.full((2, 3), 5) #Initialisation d'un tableau de 2 lignes et 3 colonnes avec la valeur 5

np.zeros((2, 3)) #Initialisation d'un tableau de 2 lignes et 3 colonnes avec la valeur 0

np.ones((2, 3)) #Initialisation d'un tableau de 2 lignes et 3 colonnes avec la valeur 1

## Utilisation du module random pour générer des valeurs aléatoires
np.random.randn(2, 3) #Initialisation d'un tableau de 2 lignes et 3 colonnes avec des valeurs aléatoires suivant une loi normale

np.linspace(0, 1, 5) #Initialisation d'un tableau de 5 valeurs espacées uniformément entre 0 et 1
np.arange(0, 10, 1) #Initialisation d'un tableau de valeurs allant de 0 à 10 avec un pas de 1

### Specifier le type de données d'un tableau
np.array([1, 2, 3], dtype=np.float32) #Initialisation d'un tableau de valeurs entières avec un type de données float32

array([1., 2., 3.], dtype=float32)

## Manipulation 
 On peut assembler les tableaux de deux manieres : 
 - **Horizontalement**
 - **Verticalement**

In [28]:
B = np.array([4, 5, 6]) ### Tab de dim 1
# On utilise : 
C = np.hstack((A, B)) #Concaténation horizontale de A et B
C.shape 

C = np.vstack((A, B)) #Concaténation verticale de A et B
C.shape

#On a egalement la possibilité de faire des concaténations avec des tableaux de dimensions différentes, mais il faut que les dimensions soient compatibles. 
#Par exemple, on peut concaténer un tableau de 2 lignes et 3 colonnes avec un tableau de 2 lignes et 2 colonnes, mais pas avec un tableau de 3 lignes et 2 colonnes.
np.concatenate((A, B), axis=0) #Concaténation verticale de A et B
#np.co      ncatenate((A, B), axis=1) #Concaténation horizontale de A et B, mais cela ne fonctionne pas car A et B n'ont pas le même nombre de lignes

## On a egalement la methode reshape qui permet de changer la forme d'un tableau.
D = np.array([[1, 2, 3], [4, 5, 6]]) #Tab de dim 2
D.shape
D.reshape(3, 2) #On change la forme de D en un tableau de 3 lignes et 2 colonnes
D.reshape(6, 1) #On change la forme de D en un tableau de 6 lignes et 1 colonne

### La methode ravel permet de transformer un tableau de n dimensions en un tableau de 1 dimension.
D.ravel() #On transforme D en un tableau de 1 dimension ou on l'applatit tout simplement 

array([1, 2, 3, 4, 5, 6])

## EXERCICE 
### Dans ce exercie on devra creer une fonction initialisation(m, n) avec m le nb lignes et n le nombre de colonnes. Elle va retourner une matrice aleatoire (m, n+1), avec une colonne biais (remplie de "1") tout a droite. 

In [ ]:
def initialisation(m, n) : 
    """
    Cette fonction permet d'initialiser un tableau de m lignes et n colonnes avec des valeurs aléatoires suivant une loi normale.
    """
    A = np.random.randn(m, n)
    A = np.concatenate((A, np.ones((A.shape[0], 1))), axis=1) #On ajoute une colonne de 1 à la fin du tableau A
    return A

print(initialisation(2, 3))

[[ 1.25534137  0.94293297  0.33811507 -0.91567184]
 [-1.42929238  0.37892202 -1.78455297 -2.39558089]]


### Test de la fonction 

In [30]:
initialisation(3, 4) #Initialisation d'un tableau de 3 lignes et 4 colonnes avec des valeurs aléatoires suivant une loi normale

array([[-0.55738999, -0.70767675, -2.10462854, -1.65133888, -0.47660123],
       [ 0.28988855,  0.54502237, -1.74868658,  0.11163498,  0.41924774],
       [ 0.22811557, -1.52584809, -1.39705698, -0.19578499,  2.19385133]])